services:
  client: # client用のコンテナ
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    tty: true
    volumes:
      - ./client:/client
    working_dir: /client
    ports:
      - 3000:3000
    networks:
      - bridge
    command: sh -c "yarn && yarn dev"

networks:
  bridge:
    driver: bridge
